### ISSUE TITLE
Sync to NPM

### ISSUE THREAD

**Issue by mullr** [nathanmacinnes/injectr#13]
I don't suppose you could do a new release to npm? Coffeescript support in particular isn't in the published version yet.

**Comment by nathanmacinnes** [comment]
I'm working in the next version at the moment, and think that'll be done in a few days. I'll release it on npm as soon as I'm happy with it.

**Comment by nathanmacinnes** [comment]
Actually, it might take me a bit longer than a few days, so I've published the existing version to npm.

**Comment by mullr** [comment]
Awesome! Thanks very much.

**Comment by nathanmacinnes** [comment]
Just so you know, my plan for the new version is not to support coffee-script out of the box, but to include a callback. This is to allow powerful features but avoid bloat. So you'd do something like this at the top of your tests:

``` javascript
var injectr.onload = function (file, content) {
    if (file.match(/\.coffee$/)) {
        return require('coffee-script').compile(content, { filename: file });
    }
    return content;
}
```

You can see my efforts so far in the `version0.4` branch. As I write this, the only feature I have yet to (re)implement is access to the context.

**Comment by mullr** [comment]
In as much as I have a vote, I'd much rather see this as a default which can be overridden. Reasoning being: 
- For a coffeescript user, this turns into 4 lines of boilerscript at the top of every test. If it's built in, it's just this chunk once inside of the module. There are enough coffeescript users around that this is an appreciable amount of boilerplate in the world. 
- Since the module is loaded on demand, there's no real harm to people who don't use coffeescript. 

The approach is reasonable though. And as before, I'm not sure I get a vote. But I do think that a bump-free experience for most users will help spread this library's usage.

**Comment by nathanmacinnes** [comment]
Having thought about it, I agree. I'll revise what I've been working on to include coffee script support directly.

**Comment by mullr** [comment]
Sweet! Thanks for your excellent work, this is really the one thing that makes TDD work for me in node.
