### ISSUE TITLE
Can't handle require statements that begin with "../"

### ISSUE THREAD

**Issue by ebdrup** [nathanmacinnes/injectr#14]
It only works if you insert "./../", this does not follow the spec for require, and is not explained in the readme.
If you do not implement support for "../", it would be cool if you at least write about it in the readme.

**Comment by nathanmacinnes** [comment]
Hi, thanks for contributing. Version 0.4 does support them, so upgrade via npm. I've just created an integration test to make sure the support can't get accidentally refactored out.

**Comment by ebdrup** [comment]
Ok, I had upgraded. But that broke tests. So I reverted the upgrade.

**Comment by nathanmacinnes** [comment]
The main reason it might have broken your tests is that version 0.4 doesn't include the global context by default. So any global objects your code uses you can include manually:

```
injectr('myapp.js', mocks, {
    console : console
});
```

It's an extra step, but it helps isolate your code so that you know exactly what it's doing during your tests.
