### ISSUE TITLE
require.resolve

### ISSUE THREAD

**Issue by nathanmacinnes** [nathanmacinnes/injectr#6]
require.resolve should be implemented.

This is a bit more tricky than the other node globals, as it needs to resolve relative to the **injectr**'d file.

**Comment by 0b10011** [comment]
You could implement something like [this](http://howtonode.org/testing-private-state-and-mocking-deps/module-loader.js) (taken from [here](http://howtonode.org/testing-private-state-and-mocking-deps)). Then `require()` should work out of the box.

**Comment by nathanmacinnes** [comment]
This is less of an issue now that other globals aren't included by default. However we should look at allowing:

``` javascript
injectr('file', {}, {
    require : {
        resolve : ...
    }
});
```

in future (unless anyone can think of a better interface), which would allow injectr to provide the require function, but the resolve function to still be added. Closing for now though.
