### ISSUE TITLE
injectr breaks debugging support in Intelli-J

### ISSUE THREAD

**Issue by stefankendall** [nathanmacinnes/injectr#9]
Using injectr prevents Intelli-J from being able to hit breakpoints.

**Comment by nathanmacinnes** [comment]
Thanks for flagging this. I'm not too familiar with Intelli-J, so would you mind forking and trying to come up with a fix, or at least a unit test which isolates the problem (ie, does the same thing Intelli-J does). If not, I'll have a look into it when I can.

**Comment by 0b10011** [comment]
Also breaks [mocha](https://github.com/visionmedia/mocha)'s HTMLCov report (specifically breaks [jscoverage](visionmedia/node-jscoverage)). Breaks injectr 3.x and 4.x from npm.

**Comment by 0b10011** [comment]
On second though, mocha can be fixed by adding the following to the second object passed to `injectr()` (may be a similar fix for Intelli-J):

```
_$jscoverage: (typeof _$jscoverage !== "undefined" ? _$jscoverage : {})
```

**Comment by nathanmacinnes** [comment]
Since globals aren't included anymore. I'm gonna call this resolved.
